### ISSUE TITLE
[discussion] enhanced build system

### ISSUE THREAD

**Issue by ff2000** [gtkd-developers/GtkD#121]
Currently GtkD is built using a hand-crafted Makefile. In order to add new modules quite some work has to be done. Copy/paste can help, but it's still easy to mess things up.
Are there already some build systems specifically targeted at building D libs/apps?
Would be cmake an option? Or waf?
Or can the Build.d-script be extended to also support non-windows platforms?

**Comment by MikeWey** [comment]
There is a build system targeting D, it's called dub and its configuration for GtkD can be found in "package.json". more information: code.dlang.org.

I like to keep the MakeFile around since dub is the fourth D build system we are supporting, after earlier attempts to create a d build system failed. (bud, compd, dsss).

As for the Build.d script, it could be extended to support other platforms.

**Comment by Ace17** [comment]
Please do not remove the Makefile!
