### ISSUE TITLE
Using GtkDGL

### ISSUE THREAD

**Issue by dazoe** [gtkd-developers/GtkD#122]
When trying to compile the SimpleGl demo, I get conflicts between gtkd.lib and gtkdgl.lib. GLContext is defined in both.
My guess is the SimpleGL demo is out of date, and i'm not sure about gtkdgl.lib

**Comment by MikeWey** [comment]
Since GTK now includes its own OpenGL support and GtkD was updated to the newer version. There are symbols which are now in both GtkD and GtkDGL. It seems like GtkDGL hasn't been tested since those were added.

I'll try to implement a workaround for GtkDGL so the symbols have different names.
In the long term, you probably want to use the gtk.GLArea from GTK/GtkD.
