### ISSUE TITLE
gio.File class missing in 3.7.0

### ISSUE THREAD

**Issue by gnunn1** [gtkd-developers/GtkD#218]
The gio.File class is no longer included in GtkD 3.7.0, instead there is only FileIF and FileT. The issue is how does one call static methods in FileIF such as parseName? The interface doesn't implement it while FileT is a template. 

I can call g_file_parse_name directly but that seems a bit ugh so I figure I must be missing something.

**Comment by MikeWey** [comment]
You're not missing anything.

gio.File and others like it were added as a workaround to be able to instantiate an interface to return from a function, this is no longer needed because of ObjectG.getInterfaceInstance.

I didn't take the static functions into account, and there implementation should be moved to the interface. I'll probably also revert gio.File for backwards compatibility, unfortunately `deprecated:` doesn't include mixed in functions.

**Comment by gnunn1** [comment]
Thanks, for now I've just implemented the method as a standalone function so no rush to fix it.

**Comment by MikeWey** [comment]
The static functions are now part of the interface.

**Comment by MikeWey** [comment]
I've reverted the opCast changes for 3.7.1, but i don't think i will add back gio.File and the ohter removed classes.

**Comment by gnunn1** [comment]
Thanks Mike, appreciate the help on this.
