### ISSUE TITLE
BuilderTest demo fails with glade file

### ISSUE THREAD

**Issue by nicesai** [gtkd-developers/GtkD#222]
I get the following error:

C:\GtkD-master\demos\builder>BuilderTest.exe builderTest.glade
Loading builderTest.glade
(BuilderTest.exe:11996): GLib-GIO-CRITICAL **: This application can not open files.

The only difference with glade file passed in arguments or generated internally is this line. The "application" is passed the input command line arguments and it doesn't seem to like it. Any idea why?
>> application.run(args);

Whats the recommended fix?

**Comment by MikeWey** [comment]
This is because the GApplicationFlags for gtk.Application are set to FLAGS_NONE telling gtk/gio that the application doesn't have any commandline arguments.

Since we handle the argument outside the application, the fix now removes the argument from args before passing it to the application.

An other option would have been to set the HANDLES_COMMAND_LINE flag and handle the commandline in the commandline signal.
